services:
  postgres:
    image: postgres:15-alpine
    container_name: restaurant_db
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432" #solve comflict
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: